name: Tests

on:
  push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@1.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 23.3.2
          elixir-version: 1.12
      - name: Install deps
        run: mix deps.get
      - name: Run tests
        run: mix test --trace